baseURL = 'https://amit-node.github.io/'
languageCode = 'en-us'
title = 'amit-node'
theme = 'maverick'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"